spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    druid:
      stat-view-servlet:
        enabled: false
      web-stat-filter:
        enabled: false
