CREATE TABLE IF NOT EXISTS sys_role (
  id BIGINT PRIMARY KEY COMMENT '主键',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  role_name VARCHAR(32) NOT NULL COMMENT '角色名',
  role_key VARCHAR(64) NOT NULL COMMENT '角色权限字符',
  data_scope TINYINT NOT NULL COMMENT '数据范围',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_tenant_role_name (tenant_id, role_name),
  UNIQUE KEY uk_tenant_role_key (tenant_id, role_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色表';

CREATE TABLE IF NOT EXISTS sys_oper_log (
  id BIGINT PRIMARY KEY COMMENT '主键',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  module_title VARCHAR(64) NOT NULL COMMENT '模块标题',
  operate_type VARCHAR(20) NOT NULL COMMENT '操作类型',
  user_id BIGINT NOT NULL COMMENT '操作人ID',
  status TINYINT NOT NULL COMMENT '状态:0成功 1失败',
  operate_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志表';

CREATE TABLE IF NOT EXISTS sys_biz_log (
  id BIGINT PRIMARY KEY COMMENT '主键',
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  biz_module VARCHAR(64) NOT NULL COMMENT '业务模块',
  biz_id BIGINT NOT NULL COMMENT '业务ID',
  field_name VARCHAR(100) NOT NULL COMMENT '字段名',
  operate_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业务变更日志表';
