-- 与《电镀ERP系统第一阶段数据库设计文档》§4.3 对齐：角色创建人/修改人、菜单时间轴、邮件记录更新时间

ALTER TABLE sys_role
  ADD COLUMN created_by BIGINT NULL COMMENT '创建人' AFTER status,
  ADD COLUMN updated_by BIGINT NULL COMMENT '修改人' AFTER created_at;

ALTER TABLE sys_menu
  ADD COLUMN created_by BIGINT NULL COMMENT '创建人' AFTER status,
  ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' AFTER created_by,
  ADD COLUMN updated_by BIGINT NULL COMMENT '修改人' AFTER created_at,
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' AFTER updated_by;

ALTER TABLE msg_email_record
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' AFTER created_at;
